#### Задание на повторение материала
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [10]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [12]:
a_1 = a.reshape(2, 6)
a_2 = a.reshape(3, 4)
a_3 = a.reshape(4, 3)
a_4 = a.reshape(6, 2)
a_5 = a.reshape(12, 1)
a_1, a_2, a_3, a_4, a_5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [15]:
a_1 = a.reshape(2, -1)
a_2 = a.reshape(3, -1)
a_3 = a.reshape(4, -1)
a_4 = a.reshape(-1, 2)
a_5 = a.reshape(-1, 1)
a_1, a_2, a_3, a_4, a_5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


ОТВЕТ: ___Нет, для доступа к значениям надо указывать вложенность a\[0\]\[0\]___

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [37]:
a = np.random.randn(3, 4)
a

array([[ 0.28037991,  0.64349506,  0.57019307,  0.97718955],
       [-0.55614256,  1.27308909, -0.00768368,  1.14108339],
       [ 1.8043214 ,  1.03560392,  0.48385034, -1.75684166]])

In [38]:
print(a.size)

12


In [39]:
b = a.flatten()
b

array([ 0.28037991,  0.64349506,  0.57019307,  0.97718955, -0.55614256,
        1.27308909, -0.00768368,  1.14108339,  1.8043214 ,  1.03560392,
        0.48385034, -1.75684166])

In [40]:
print(b.size)

12


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [44]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [50]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [53]:
a.shape, b.shape

((10,), (1, 10))

In [54]:
# первый массив одномерный, второй двумерный

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [78]:
b = np.ones([3,2])
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [79]:
a = np.zeros([b.shape[0]-1, 2])
a

array([[0., 0.],
       [0., 0.]])

In [80]:
v = np.vstack([a, b])
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [81]:
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [84]:
a = [i for i in range(0,12)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [85]:
A = np.reshape(a, [4, 3])
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
At = np.transpose(A)
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [88]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [89]:
B.size

16

In [111]:
np.linalg.det(B)

0.0

In [93]:
# обратную матрицу построить нельзя, так как определитель исходной матрицы равен нулю.

Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [102]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [121]:
c = np.random.randint(0, 16, 16)
c

array([ 7,  2,  5,  4,  1,  7, 11, 13,  5,  1, 15, 11,  4,  0, 11,  9])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [122]:
C = np.reshape(c , [4, -1])
C

array([[ 7,  2,  5,  4],
       [ 1,  7, 11, 13],
       [ 5,  1, 15, 11],
       [ 4,  0, 11,  9]])

In [123]:
D = B + C * 10
D

array([[ 75,  34,  73,  72],
       [ 24, 120, 196, 252],
       [ 73,  96, 299, 322],
       [ 72, 122, 322, 392]])

In [124]:
np.linalg.det(D)

33790400.00000005

In [125]:
np.linalg.matrix_rank(D)

4

In [127]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01610043, -0.00531689, -0.00816208,  0.00716535],
       [ 0.00715114,  0.02249692,  0.00430063, -0.01930844],
       [-0.0055933 ,  0.00488364,  0.03278919, -0.02904612],
       [-0.00058833, -0.01003658, -0.02677328,  0.03110351]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [134]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.]])

In [136]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,   2,   5,  32],
       [ 14,  50,  86,  13],
       [  5,  86, 149,  11],
       [  4,   0,  11, 302]])